# Generated by Django 2.2.19 on 2021-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='about',
        ),
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='health',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mana',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
